// i18n bootstrap for the Lit SPA.
//
// Wires @lit/localize's runtime mode so each translation lives in its
// own ES module that we only fetch when the user actually switches to
// that locale. The locale is sourced from Home Assistant via the
// ``rune-init`` bridge handshake (see ``src/api/bridge.ts``); if HA
// hasn't sent it yet (e.g. cold start) we render in English and swap
// locales the moment the bridge replies.
//
// Shoelace components are localized in lockstep — ``setLocale()`` here
// also calls Shoelace's ``registerTranslation`` so dropdowns, dialogs,
// and tooltips render in the same language as the rest of the UI.

import { configureLocalization } from "@lit/localize";
import { update as shoelaceUpdate } from "@shoelace-style/localize";
import enShoelace from "@shoelace-style/shoelace/dist/translations/en.js";
import esShoelace from "@shoelace-style/shoelace/dist/translations/es.js";
import { registerTranslation } from "@shoelace-style/shoelace/dist/utilities/localize.js";

import { allLocales, sourceLocale, targetLocales } from "@/generated/locale-codes.js";
import { store } from "@/state/store.js";

// ``LocaleModule`` isn't re-exported from ``@lit/localize`` but is part
// of its public runtime-mode contract. We import it from the package's
// internal types path so the bundle still typechecks against the real
// shape (templates keyed by id → ``TemplateLike``).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
import type { LocaleModule } from "@lit/localize/internal/types.js";

const SHOELACE_TRANSLATIONS: Record<string, unknown> = {
  en: enShoelace,
  es: esShoelace,
};

export const { getLocale, setLocale } = configureLocalization({
  sourceLocale,
  targetLocales: [...targetLocales],
  // Lazy-imported locale modules are generated by ``lit-localize build``
  // into ``src/generated/locales/<locale>.ts``. ``import.meta.glob`` lets
  // Vite bundle every target locale into the single-file SPA so the
  // runtime switch never hits the network — critical because the panel
  // runs inside an iframe in HA and may not have CORS access to its own
  // origin for late fetches.
  loadLocale: async (locale: string): Promise<LocaleModule> => {
    const modules = import.meta.glob<LocaleModule>("./generated/locales/*.ts");
    const match = modules[`./generated/locales/${locale}.ts`];
    if (!match) {
      throw new Error(`[rune-i18n] unknown locale module: ${locale}`);
    }
    return match();
  },
});

let shoelaceLocale = sourceLocale;

function syncShoelaceLocale(locale: string): void {
  if (locale === shoelaceLocale) return;
  const translation = SHOELACE_TRANSLATIONS[locale];
  if (translation) {
    registerTranslation(translation as Parameters<typeof registerTranslation>[0]);
    shoelaceLocale = locale;
    void shoelaceUpdate();
  }
}

function normalizeLocale(locale: string): string {
  // Match exact codes first (e.g. ``pt-BR``), then fall back to the
  // base language (``pt``). Unknown codes fall through to the source.
  if ((allLocales as readonly string[]).includes(locale)) return locale;
  const base = locale.split(/[-_]/)[0];
  if (base && (allLocales as readonly string[]).includes(base)) return base;
  return sourceLocale;
}

let bootstrapped = false;

export async function bootstrapI18n(): Promise<void> {
  if (bootstrapped) return;
  bootstrapped = true;

  // Register every Shoelace translation we ship up front so locale
  // switches are instant — the data is already in the bundle.
  for (const [code, translation] of Object.entries(SHOELACE_TRANSLATIONS)) {
    void code;
    registerTranslation(translation as Parameters<typeof registerTranslation>[0]);
  }

  // If the bridge has already pushed a locale (warm SPA reload, fast
  // machines), honour it. Otherwise stay on the source locale until the
  // bridge replies.
  if (store.locale) {
    const target = normalizeLocale(store.locale);
    syncShoelaceLocale(target);
    if (target !== sourceLocale) {
      try {
        await setLocale(target);
      } catch (err) {
        console.warn(`[rune-i18n] failed to switch to ${target}:`, err);
      }
    }
  }
}

let bridgeListenerInstalled = false;

export function installBridgeLocaleSync(): void {
  if (bridgeListenerInstalled) return;
  bridgeListenerInstalled = true;

  // The bridge listener in ``api/bridge.ts`` mutates ``store.locale``
  // directly when ``rune-init`` arrives. We react to that here by
  // swapping the locale once and only once per change.
  let lastSeen = "";
  const tick = async (): Promise<void> => {
    const current = store.locale;
    if (!current || current === lastSeen) return;
    lastSeen = current;
    const target = normalizeLocale(current);
    syncShoelaceLocale(target);
    try {
      await setLocale(target);
    } catch (err) {
      console.warn(`[rune-i18n] failed to switch to ${target}:`, err);
    }
  };

  // Subscribe to store updates via the same channel the AppShell uses.
  // Avoids a second listener registry just for locale changes.
  import("@/state/store.js")
    .then(({ subscribe }) => {
      subscribe(() => {
        void tick();
      });
    })
    .catch((err) => {
      console.warn("[rune-i18n] could not subscribe to store:", err);
    });
}
