// i18n bootstrap for the Lit SPA.
//
// Wires @lit/localize's runtime mode so each translation lives in its
// own ES module that we only fetch when the user actually switches to
// that locale. Locale resolution priority:
//
//   1. User's manual preference (localStorage ``rune-locale``) — wins
//      whenever it's set to a specific language (``en`` / ``es``).
//   2. Home Assistant's ``hass.config.language`` — used when the user
//      chose ``auto`` (the default).
//   3. Source locale (``en``) — last-resort fallback if HA hasn't
//      replied yet and the pref is ``auto``.
//
// Shoelace components are localized in lockstep — every time we
// change the locale we also call ``registerTranslation`` so dropdowns,
// dialogs, and tooltips render in the same language as the rest of
// the UI.

import { configureLocalization } from "@lit/localize";
import { update as shoelaceUpdate } from "@shoelace-style/localize";
import enShoelace from "@shoelace-style/shoelace/dist/translations/en.js";
import esShoelace from "@shoelace-style/shoelace/dist/translations/es.js";
import { registerTranslation } from "@shoelace-style/shoelace/dist/utilities/localize.js";

import { allLocales, sourceLocale, targetLocales } from "@/generated/locale-codes.js";
import { getLocalePref, onLocalePrefChange } from "@/state/locale-pref.js";
import { store, subscribe } from "@/state/store.js";

// ``LocaleModule`` isn't re-exported from ``@lit/localize`` but is part
// of its public runtime-mode contract. We import it from the package's
// internal types path so the bundle still typechecks against the real
// shape (templates keyed by id → ``TemplateLike``).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
import type { LocaleModule } from "@lit/localize/internal/types.js";

const SHOELACE_TRANSLATIONS: Record<string, unknown> = {
  en: enShoelace,
  es: esShoelace,
};

export const { getLocale, setLocale } = configureLocalization({
  sourceLocale,
  targetLocales: [...targetLocales],
  // Lazy-imported locale modules are generated by ``lit-localize build``
  // into ``src/generated/locales/<locale>.ts``. ``import.meta.glob`` lets
  // Vite bundle every target locale into the single-file SPA so the
  // runtime switch never hits the network — critical because the panel
  // runs inside an iframe in HA and may not have CORS access to its own
  // origin for late fetches.
  loadLocale: async (locale: string): Promise<LocaleModule> => {
    const modules = import.meta.glob<LocaleModule>("./generated/locales/*.ts");
    const match = modules[`./generated/locales/${locale}.ts`];
    if (!match) {
      throw new Error(`[rune-i18n] unknown locale module: ${locale}`);
    }
    return match();
  },
});

let shoelaceLocale = sourceLocale;

function syncShoelaceLocale(locale: string): void {
  if (locale === shoelaceLocale) return;
  const translation = SHOELACE_TRANSLATIONS[locale];
  if (translation) {
    registerTranslation(translation as Parameters<typeof registerTranslation>[0]);
    shoelaceLocale = locale;
    void shoelaceUpdate();
  }
}

function normalizeLocale(locale: string): string {
  // Match exact codes first (e.g. ``pt-BR``), then fall back to the
  // base language (``pt``). Unknown codes fall through to the source.
  if ((allLocales as readonly string[]).includes(locale)) return locale;
  const base = locale.split(/[-_]/)[0];
  if (base && (allLocales as readonly string[]).includes(base)) return base;
  return sourceLocale;
}

/** Resolve which locale we should *actually* use right now, given the
 *  user's stored preference and whatever HA has reported via the
 *  bridge. Returns a normalized locale code, never empty. */
export function resolveActiveLocale(): string {
  const pref = getLocalePref();
  if (pref !== "auto") return normalizeLocale(pref);
  if (store.locale) return normalizeLocale(store.locale);
  return sourceLocale;
}

async function applyLocale(locale: string): Promise<void> {
  const target = normalizeLocale(locale);
  syncShoelaceLocale(target);
  if (target === getLocale()) return;
  try {
    await setLocale(target);
  } catch (err) {
    console.warn(`[rune-i18n] failed to switch to ${target}:`, err);
  }
}

let bootstrapped = false;

export async function bootstrapI18n(): Promise<void> {
  if (bootstrapped) return;
  bootstrapped = true;

  // Register every Shoelace translation we ship up front so locale
  // switches are instant — the data is already in the bundle.
  for (const translation of Object.values(SHOELACE_TRANSLATIONS)) {
    registerTranslation(translation as Parameters<typeof registerTranslation>[0]);
  }

  await applyLocale(resolveActiveLocale());
}

let bridgeListenerInstalled = false;

export function installBridgeLocaleSync(): void {
  if (bridgeListenerInstalled) return;
  bridgeListenerInstalled = true;

  // When the user flips the locale toggle we honour it immediately,
  // overriding whatever HA might report next.
  onLocalePrefChange(() => {
    void applyLocale(resolveActiveLocale());
  });

  // The bridge listener in ``api/bridge.ts`` mutates ``store.locale``
  // directly when ``rune-init`` arrives. We only react when the user
  // is on ``auto`` — otherwise their preference wins and we ignore
  // HA's report.
  let lastSeen = "";
  subscribe(() => {
    if (getLocalePref() !== "auto") return;
    const current = store.locale;
    if (!current || current === lastSeen) return;
    lastSeen = current;
    void applyLocale(current);
  });
}
